/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;


import java.awt.Color;

/**
 *
 * @author HP
 */
public class AddReservation extends javax.swing.JDialog {
    
    
    int xMouse, yMouse;
    public AddReservation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        outBtn = new javax.swing.JPanel();
        outTxt = new javax.swing.JLabel();
        information = new javax.swing.JLabel();
        idReservationTxt = new javax.swing.JLabel();
        idReservationText = new javax.swing.JTextField();
        Separator1 = new javax.swing.JSeparator();
        customerNameTxt = new javax.swing.JLabel();
        customerNameText = new javax.swing.JTextField();
        Separator2 = new javax.swing.JSeparator();
        numberOfPeopleTxt = new javax.swing.JLabel();
        numberOfPeopleText = new javax.swing.JTextField();
        Separator3 = new javax.swing.JSeparator();
        timeTxt = new javax.swing.JLabel();
        timeText = new javax.swing.JTextField();
        Separator4 = new javax.swing.JSeparator();
        dateTxt = new javax.swing.JLabel();
        dateText = new javax.swing.JTextField();
        Separator5 = new javax.swing.JSeparator();
        saveBtn = new javax.swing.JPanel();
        saveTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(229, 180, 139));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        outBtn.setBackground(new java.awt.Color(229, 180, 139));

        outTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        outTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outTxt.setText("X");
        outTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        outTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                outTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout outBtnLayout = new javax.swing.GroupLayout(outBtn);
        outBtn.setLayout(outBtnLayout);
        outBtnLayout.setHorizontalGroup(
            outBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(outTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        outBtnLayout.setVerticalGroup(
            outBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(outTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        information.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        information.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        information.setText("Reserva");

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(information, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addComponent(outBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(information, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 620, 80));

        idReservationTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        idReservationTxt.setText("ID de Reserva");
        background.add(idReservationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, -1));

        idReservationText.setForeground(new java.awt.Color(204, 204, 204));
        idReservationText.setText("Ingresar el ID de reserva");
        idReservationText.setBorder(null);
        idReservationText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idReservationTextFocusLost(evt);
            }
        });
        idReservationText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idReservationTextMousePressed(evt);
            }
        });
        idReservationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReservationTextActionPerformed(evt);
            }
        });
        background.add(idReservationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 400, 30));

        Separator1.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 510, -1));

        customerNameTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        customerNameTxt.setText("Nombre del Cliente");
        background.add(customerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, -1));

        customerNameText.setForeground(new java.awt.Color(204, 204, 204));
        customerNameText.setText("Ingresar el nombre del cliente");
        customerNameText.setBorder(null);
        customerNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameTextFocusLost(evt);
            }
        });
        customerNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerNameTextMousePressed(evt);
            }
        });
        background.add(customerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 400, 30));

        Separator2.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 510, -1));

        numberOfPeopleTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        numberOfPeopleTxt.setText("Cantidad de personas");
        background.add(numberOfPeopleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, -1));

        numberOfPeopleText.setForeground(new java.awt.Color(204, 204, 204));
        numberOfPeopleText.setText("Ingresar la cantidad de personas");
        numberOfPeopleText.setBorder(null);
        numberOfPeopleText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberOfPeopleTextFocusLost(evt);
            }
        });
        numberOfPeopleText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numberOfPeopleTextMousePressed(evt);
            }
        });
        background.add(numberOfPeopleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 400, 30));

        Separator3.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 510, -1));

        timeTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        timeTxt.setText("Hora");
        background.add(timeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, -1));

        timeText.setForeground(new java.awt.Color(204, 204, 204));
        timeText.setText("Ingresar la hora");
        timeText.setBorder(null);
        timeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                timeTextFocusLost(evt);
            }
        });
        timeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timeTextMousePressed(evt);
            }
        });
        background.add(timeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 400, 30));

        Separator4.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 510, -1));

        dateTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        dateTxt.setText("Fecha");
        background.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 120, -1));

        dateText.setForeground(new java.awt.Color(204, 204, 204));
        dateText.setText("Ingresar la fecha");
        dateText.setBorder(null);
        dateText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateTextFocusLost(evt);
            }
        });
        dateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dateTextMousePressed(evt);
            }
        });
        background.add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 400, 30));

        Separator5.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 510, -1));

        saveBtn.setBackground(new java.awt.Color(229, 180, 139));

        saveTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        saveTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveTxt.setText("Guardar");
        saveTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout saveBtnLayout = new javax.swing.GroupLayout(saveBtn);
        saveBtn.setLayout(saveBtnLayout);
        saveBtnLayout.setHorizontalGroup(
            saveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveBtnLayout.createSequentialGroup()
                .addComponent(saveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        saveBtnLayout.setVerticalGroup(
            saveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveBtnLayout.createSequentialGroup()
                .addComponent(saveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        background.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outTxtMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_outTxtMouseClicked

    private void outTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outTxtMouseEntered
        outBtn.setBackground(new Color(229, 127, 95));
        outTxt.setForeground(Color.white);
    }//GEN-LAST:event_outTxtMouseEntered

    private void outTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outTxtMouseExited
        outBtn.setBackground(new Color(229, 180, 139));
        outTxt.setForeground(Color.black);
    }//GEN-LAST:event_outTxtMouseExited

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void idReservationTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idReservationTextFocusLost
        if (idReservationText.getText().trim().isEmpty()) {
            idReservationText.setText("Ingresar el ID de reserva");
            idReservationText.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_idReservationTextFocusLost

    private void idReservationTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idReservationTextMousePressed
        if (idReservationText.getText().equals("Ingresar el ID de reserva")) {
            idReservationText.setText("");
            idReservationText.setForeground(Color.black);
        }
    }//GEN-LAST:event_idReservationTextMousePressed

    private void idReservationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReservationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idReservationTextActionPerformed

    private void customerNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameTextFocusLost
        if (customerNameText.getText().trim().isEmpty()) {
            customerNameText.setText("Ingresar el nombre del cliente");
            customerNameText.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_customerNameTextFocusLost

    private void customerNameTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNameTextMousePressed
        if(customerNameText.getText().equalsIgnoreCase("Ingresar el nombre del cliente")){
            customerNameText.setText("");
            customerNameText.setForeground(Color.black);
        }
    }//GEN-LAST:event_customerNameTextMousePressed

    private void numberOfPeopleTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberOfPeopleTextFocusLost
        if (numberOfPeopleText.getText().trim().isEmpty()) {
            numberOfPeopleText.setText("Ingresar la cantidad de personas");
            numberOfPeopleText.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_numberOfPeopleTextFocusLost

    private void numberOfPeopleTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberOfPeopleTextMousePressed
        if(numberOfPeopleText.getText().equalsIgnoreCase("Ingresar la cantidad de personas")){
            numberOfPeopleText.setText("");
            numberOfPeopleText.setForeground(Color.black);
        }
    }//GEN-LAST:event_numberOfPeopleTextMousePressed

    private void timeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timeTextFocusLost
        if (timeText.getText().trim().isEmpty()) {
            timeText.setText("Ingresar la hora");
            timeText.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_timeTextFocusLost

    private void timeTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTextMousePressed
        if(timeText.getText().equalsIgnoreCase("Ingresar la hora")){
            timeText.setText("");
            timeText.setForeground(Color.black);
        }
    }//GEN-LAST:event_timeTextMousePressed

    private void dateTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTextFocusLost
        if (dateText.getText().trim().isEmpty()) {
            dateText.setText("Ingresar la fecha");
            dateText.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_dateTextFocusLost

    private void dateTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTextMousePressed
        if(dateText.getText().equalsIgnoreCase("Ingresar la fecha")){
            dateText.setText("");
            dateText.setForeground(Color.black);
        }
    }//GEN-LAST:event_dateTextMousePressed

    private void saveTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTxtMouseClicked

    }//GEN-LAST:event_saveTxtMouseClicked

    private void saveTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTxtMouseEntered
        saveBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_saveTxtMouseEntered

    private void saveTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTxtMouseExited
        saveBtn.setBackground(new Color(229, 180, 139));
    }//GEN-LAST:event_saveTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddReservation dialog = new AddReservation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSeparator Separator4;
    private javax.swing.JSeparator Separator5;
    private javax.swing.JPanel background;
    private javax.swing.JPanel bar;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JLabel customerNameTxt;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel dateTxt;
    private javax.swing.JTextField idReservationText;
    private javax.swing.JLabel idReservationTxt;
    private javax.swing.JLabel information;
    private javax.swing.JTextField numberOfPeopleText;
    private javax.swing.JLabel numberOfPeopleTxt;
    private javax.swing.JPanel outBtn;
    private javax.swing.JLabel outTxt;
    private javax.swing.JPanel saveBtn;
    private javax.swing.JLabel saveTxt;
    private javax.swing.JTextField timeText;
    private javax.swing.JLabel timeTxt;
    // End of variables declaration//GEN-END:variables
}
