/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;


import java.awt.Color;

/**
 *
 * @author HP
 */
public class CancelReservation extends javax.swing.JDialog {

    int xMouse, yMouse;
    public CancelReservation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        information = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        salirBtn = new javax.swing.JPanel();
        salirTxt = new javax.swing.JLabel();
        cancelText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        Separator2 = new javax.swing.JSeparator();
        confirmBtn = new javax.swing.JPanel();
        confirmTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        information.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        information.setText("Introduzca el ID de la reservación a cancelar:");
        background.add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        bar.setBackground(new java.awt.Color(229, 180, 139));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        salirBtn.setBackground(new java.awt.Color(229, 180, 139));

        salirTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salirTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirTxt.setText("X");
        salirTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirBtnLayout.createSequentialGroup()
                .addComponent(salirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addGap(0, 370, Short.MAX_VALUE)
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        background.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        cancelText.setForeground(new java.awt.Color(204, 204, 204));
        cancelText.setText("Introduzca el ID a buscar");
        cancelText.setBorder(null);
        cancelText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cancelTextFocusLost(evt);
            }
        });
        cancelText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelTextMousePressed(evt);
            }
        });
        cancelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTextActionPerformed(evt);
            }
        });
        background.add(cancelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("ID de Reservación");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 20));
        background.add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, -1));
        background.add(Separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, -1));

        confirmBtn.setBackground(new java.awt.Color(229, 180, 139));

        confirmTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirmTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmTxt.setText("Confirmar");
        confirmTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout confirmBtnLayout = new javax.swing.GroupLayout(confirmBtn);
        confirmBtn.setLayout(confirmBtnLayout);
        confirmBtnLayout.setHorizontalGroup(
            confirmBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmBtnLayout.createSequentialGroup()
                .addComponent(confirmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        confirmBtnLayout.setVerticalGroup(
            confirmBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_salirTxtMouseClicked

    private void salirTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseEntered
        salirBtn.setBackground(new Color(229, 127, 95));
        salirTxt.setForeground(Color.white);
    }//GEN-LAST:event_salirTxtMouseEntered

    private void salirTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseExited
        salirBtn.setBackground(new Color(229, 180, 139));
        salirTxt.setForeground(Color.black);
    }//GEN-LAST:event_salirTxtMouseExited

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void cancelTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cancelTextFocusLost
        if (cancelText.getText().trim().isEmpty()) {
            cancelText.setText("Introduzca el ID a buscar");
            cancelText.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_cancelTextFocusLost

    private void cancelTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTextMousePressed
        if (cancelText.getText().equals("Introduzca el ID a buscar")) {
            cancelText.setText("");
            cancelText.setForeground(Color.black);
        }
    }//GEN-LAST:event_cancelTextMousePressed

    private void cancelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelTextActionPerformed

    private void confirmTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmTxtMouseClicked
        
    }//GEN-LAST:event_confirmTxtMouseClicked

    private void confirmTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmTxtMouseEntered
        confirmBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_confirmTxtMouseEntered

    private void confirmTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmTxtMouseExited
        confirmBtn.setBackground(new Color(229, 180, 139));
    }//GEN-LAST:event_confirmTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CancelReservation dialog = new CancelReservation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JPanel background;
    private javax.swing.JPanel bar;
    private javax.swing.JTextField cancelText;
    private javax.swing.JPanel confirmBtn;
    private javax.swing.JLabel confirmTxt;
    private javax.swing.JLabel information;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JLabel salirTxt;
    // End of variables declaration//GEN-END:variables
}
