/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;


import java.awt.Color;

/**
 *
 * @author HP
 */
public class FrameMain extends javax.swing.JFrame {
       
    int xMouse , yMouse;
    public FrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        restaurantImage = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        moveFrame = new javax.swing.JPanel();
        outBtn = new javax.swing.JPanel();
        salirTxt = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JPanel();
        cancelTxt = new javax.swing.JLabel();
        addBtn = new javax.swing.JPanel();
        addTxt = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JPanel();
        confirmTxt = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        updateTxt = new javax.swing.JLabel();
        listBtn = new javax.swing.JPanel();
        listTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        restaurantImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restaurant~5.jpg"))); // NOI18N
        background.add(restaurantImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -6, 310, 510));

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/m1.jpg"))); // NOI18N
        title.setText("Sistema de Reservaciones");
        background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 360, 110));

        moveFrame.setBackground(new java.awt.Color(255, 255, 255));
        moveFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveFrameMouseDragged(evt);
            }
        });
        moveFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveFrameMousePressed(evt);
            }
        });

        outBtn.setBackground(new java.awt.Color(255, 255, 255));

        salirTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salirTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirTxt.setText("X");
        salirTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout outBtnLayout = new javax.swing.GroupLayout(outBtn);
        outBtn.setLayout(outBtnLayout);
        outBtnLayout.setHorizontalGroup(
            outBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        outBtnLayout.setVerticalGroup(
            outBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout moveFrameLayout = new javax.swing.GroupLayout(moveFrame);
        moveFrame.setLayout(moveFrameLayout);
        moveFrameLayout.setHorizontalGroup(
            moveFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveFrameLayout.createSequentialGroup()
                .addComponent(outBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 763, Short.MAX_VALUE))
        );
        moveFrameLayout.setVerticalGroup(
            moveFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(moveFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        cancelBtn.setBackground(new java.awt.Color(229, 180, 139));

        cancelTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelTxt.setForeground(new java.awt.Color(255, 255, 255));
        cancelTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelTxt.setText("Cancelar Reserva");
        cancelTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cancelBtnLayout = new javax.swing.GroupLayout(cancelBtn);
        cancelBtn.setLayout(cancelBtnLayout);
        cancelBtnLayout.setHorizontalGroup(
            cancelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        cancelBtnLayout.setVerticalGroup(
            cancelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 150, 40));

        addBtn.setBackground(new java.awt.Color(229, 180, 139));

        addTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addTxt.setForeground(new java.awt.Color(255, 255, 255));
        addTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addTxt.setText("Añadir Reserva");
        addTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout addBtnLayout = new javax.swing.GroupLayout(addBtn);
        addBtn.setLayout(addBtnLayout);
        addBtnLayout.setHorizontalGroup(
            addBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        addBtnLayout.setVerticalGroup(
            addBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, 40));

        confirmBtn.setBackground(new java.awt.Color(229, 180, 139));

        confirmTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmTxt.setForeground(new java.awt.Color(255, 255, 255));
        confirmTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmTxt.setText("Confirmar Reserva");
        confirmTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout confirmBtnLayout = new javax.swing.GroupLayout(confirmBtn);
        confirmBtn.setLayout(confirmBtnLayout);
        confirmBtnLayout.setHorizontalGroup(
            confirmBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmBtnLayout.createSequentialGroup()
                .addComponent(confirmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        confirmBtnLayout.setVerticalGroup(
            confirmBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 40));

        updateBtn.setBackground(new java.awt.Color(229, 180, 139));

        updateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTxt.setForeground(new java.awt.Color(255, 255, 255));
        updateTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateTxt.setText("Actualizar Reserva");
        updateTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addComponent(updateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 150, 40));

        listBtn.setBackground(new java.awt.Color(229, 180, 139));

        listTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listTxt.setForeground(new java.awt.Color(255, 255, 255));
        listTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listTxt.setText("Lista de Reserva");
        listTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout listBtnLayout = new javax.swing.GroupLayout(listBtn);
        listBtn.setLayout(listBtnLayout);
        listBtnLayout.setHorizontalGroup(
            listBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        listBtnLayout.setVerticalGroup(
            listBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(listBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseClicked
        System.exit(-1);
    }//GEN-LAST:event_salirTxtMouseClicked

    private void salirTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseEntered
        outBtn.setBackground(new Color(229,127,95));
        salirTxt.setForeground(Color.white);
    }//GEN-LAST:event_salirTxtMouseEntered

    private void salirTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseExited
        outBtn.setBackground(Color.white);
        salirTxt.setForeground(Color.black);
    }//GEN-LAST:event_salirTxtMouseExited

    private void moveFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveFrameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_moveFrameMouseDragged

    private void moveFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveFrameMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_moveFrameMousePressed

    private void cancelTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTxtMouseClicked
       
    }//GEN-LAST:event_cancelTxtMouseClicked

    private void cancelTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTxtMouseEntered
        cancelBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_cancelTxtMouseEntered

    private void cancelTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTxtMouseExited
        cancelBtn.setBackground(new Color(229,180,139));
    }//GEN-LAST:event_cancelTxtMouseExited

    private void addTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTxtMouseClicked
        
    }//GEN-LAST:event_addTxtMouseClicked

    private void addTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTxtMouseEntered
        addBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_addTxtMouseEntered

    private void addTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTxtMouseExited
        addBtn.setBackground(new Color(229,180,139));
    }//GEN-LAST:event_addTxtMouseExited

    private void confirmTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmTxtMouseClicked
        
    }//GEN-LAST:event_confirmTxtMouseClicked

    private void confirmTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmTxtMouseEntered
        confirmBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_confirmTxtMouseEntered

    private void confirmTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmTxtMouseExited
        confirmBtn.setBackground(new Color(229,180,139));
    }//GEN-LAST:event_confirmTxtMouseExited

    private void updateTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTxtMouseClicked
        
    }//GEN-LAST:event_updateTxtMouseClicked

    private void updateTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTxtMouseEntered
        updateBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_updateTxtMouseEntered

    private void updateTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTxtMouseExited
        updateBtn.setBackground(new Color(229,180,139));
    }//GEN-LAST:event_updateTxtMouseExited

    private void listTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTxtMouseClicked
        
    }//GEN-LAST:event_listTxtMouseClicked

    private void listTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTxtMouseEntered
        listBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_listTxtMouseEntered

    private void listTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTxtMouseExited
        listBtn.setBackground(new Color(229,180,139));
    }//GEN-LAST:event_listTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBtn;
    private javax.swing.JLabel addTxt;
    private javax.swing.JPanel background;
    private javax.swing.JPanel cancelBtn;
    private javax.swing.JLabel cancelTxt;
    private javax.swing.JPanel confirmBtn;
    private javax.swing.JLabel confirmTxt;
    private javax.swing.JPanel listBtn;
    private javax.swing.JLabel listTxt;
    private javax.swing.JPanel moveFrame;
    private javax.swing.JPanel outBtn;
    private javax.swing.JLabel restaurantImage;
    private javax.swing.JLabel salirTxt;
    private javax.swing.JLabel title;
    private javax.swing.JPanel updateBtn;
    private javax.swing.JLabel updateTxt;
    // End of variables declaration//GEN-END:variables
}
