/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class UpdateReservation extends javax.swing.JDialog {
    int xMouse, yMouse;
    /**
     * Creates new form UpdateReservation
     */
    public UpdateReservation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        salirBtn = new javax.swing.JPanel();
        salirTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customerNameTxt = new javax.swing.JLabel();
        customerNameText = new javax.swing.JTextField();
        Separator1 = new javax.swing.JSeparator();
        numberOfPeopleTxt = new javax.swing.JLabel();
        numberOfPeopleText = new javax.swing.JTextField();
        Separator2 = new javax.swing.JSeparator();
        timeTxt = new javax.swing.JLabel();
        timeText = new javax.swing.JTextField();
        Separator3 = new javax.swing.JSeparator();
        dateTxt = new javax.swing.JLabel();
        dateText = new javax.swing.JTextField();
        Separator4 = new javax.swing.JSeparator();
        saveBtn = new javax.swing.JPanel();
        saveTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(229, 180, 139));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        salirBtn.setBackground(new java.awt.Color(229, 180, 139));

        salirTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salirTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirTxt.setText("X");
        salirTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salirBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salirBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizar Reserva");

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 620, 80));

        customerNameTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        customerNameTxt.setText("Nombre del Cliente");
        background.add(customerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        customerNameText.setForeground(new java.awt.Color(204, 204, 204));
        customerNameText.setText("Ingresar el nombre del cliente");
        customerNameText.setBorder(null);
        customerNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameTextFocusLost(evt);
            }
        });
        customerNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerNameTextMousePressed(evt);
            }
        });
        background.add(customerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 400, 30));

        Separator1.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 510, -1));

        numberOfPeopleTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        numberOfPeopleTxt.setText("Cantidad de personas");
        background.add(numberOfPeopleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, -1));

        numberOfPeopleText.setForeground(new java.awt.Color(204, 204, 204));
        numberOfPeopleText.setText("Ingresar la cantidad de personas");
        numberOfPeopleText.setBorder(null);
        numberOfPeopleText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberOfPeopleTextFocusLost(evt);
            }
        });
        numberOfPeopleText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numberOfPeopleTextMousePressed(evt);
            }
        });
        background.add(numberOfPeopleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 400, 30));

        Separator2.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 510, -1));

        timeTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        timeTxt.setText("Hora");
        background.add(timeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, -1));

        timeText.setForeground(new java.awt.Color(204, 204, 204));
        timeText.setText("Ingresar la hora");
        timeText.setBorder(null);
        timeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                timeTextFocusLost(evt);
            }
        });
        timeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timeTextMousePressed(evt);
            }
        });
        background.add(timeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 400, 30));

        Separator3.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 510, -1));

        dateTxt.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        dateTxt.setText("Fecha");
        background.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, -1));

        dateText.setForeground(new java.awt.Color(204, 204, 204));
        dateText.setText("Ingresar la fecha");
        dateText.setBorder(null);
        dateText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateTextFocusLost(evt);
            }
        });
        dateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dateTextMousePressed(evt);
            }
        });
        background.add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 400, 30));

        Separator4.setForeground(new java.awt.Color(51, 51, 51));
        background.add(Separator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 510, -1));

        saveBtn.setBackground(new java.awt.Color(229, 180, 139));

        saveTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        saveTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveTxt.setText("Guardar");
        saveTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout saveBtnLayout = new javax.swing.GroupLayout(saveBtn);
        saveBtn.setLayout(saveBtnLayout);
        saveBtnLayout.setHorizontalGroup(
            saveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveBtnLayout.createSequentialGroup()
                .addComponent(saveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        saveBtnLayout.setVerticalGroup(
            saveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveBtnLayout.createSequentialGroup()
                .addComponent(saveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        background.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_salirTxtMouseClicked

    private void salirTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseEntered
        salirBtn.setBackground(new Color(229, 127, 95));
        salirTxt.setForeground(Color.white);
    }//GEN-LAST:event_salirTxtMouseEntered

    private void salirTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseExited
        salirBtn.setBackground(new Color(229, 180, 139));
        salirTxt.setForeground(Color.black);
    }//GEN-LAST:event_salirTxtMouseExited

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void customerNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameTextFocusLost
        if (customerNameText.getText().trim().isEmpty()) {
            customerNameText.setText("Ingresar el nombre del cliente");
            customerNameText.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_customerNameTextFocusLost

    private void customerNameTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNameTextMousePressed
        if (customerNameText.getText().equalsIgnoreCase("Ingresar el nombre del cliente")) {
            customerNameText.setText("");
            customerNameText.setForeground(Color.black);
        }
    }//GEN-LAST:event_customerNameTextMousePressed

    private void numberOfPeopleTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberOfPeopleTextFocusLost
        if (numberOfPeopleText.getText().trim().isEmpty()) {
            numberOfPeopleText.setText("Ingresar la cantidad de personas");
            numberOfPeopleText.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_numberOfPeopleTextFocusLost

    private void numberOfPeopleTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberOfPeopleTextMousePressed
        if (numberOfPeopleText.getText().equalsIgnoreCase("Ingresar la cantidad de personas")) {
            numberOfPeopleText.setText("");
            numberOfPeopleText.setForeground(Color.black);
        }
    }//GEN-LAST:event_numberOfPeopleTextMousePressed

    private void timeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timeTextFocusLost
        if (timeText.getText().trim().isEmpty()) {
            timeText.setText("Ingresar la hora");
            timeText.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_timeTextFocusLost

    private void timeTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTextMousePressed
        if (timeText.getText().equalsIgnoreCase("Ingresar la hora")) {
            timeText.setText("");
            timeText.setForeground(Color.black);
        }
    }//GEN-LAST:event_timeTextMousePressed

    private void dateTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTextFocusLost
        if (dateText.getText().trim().isEmpty()) {
            dateText.setText("Ingresar la fecha");
            dateText.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_dateTextFocusLost

    private void dateTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTextMousePressed
        if (dateText.getText().equalsIgnoreCase("Ingresar la fecha")) {
            dateText.setText("");
            dateText.setForeground(Color.black);
        }
    }//GEN-LAST:event_dateTextMousePressed

    private void saveTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTxtMouseClicked
        
    }//GEN-LAST:event_saveTxtMouseClicked

    private void saveTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTxtMouseEntered
        saveBtn.setBackground(new Color(247, 194, 150));
    }//GEN-LAST:event_saveTxtMouseEntered

    private void saveTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTxtMouseExited
        saveBtn.setBackground(new Color(229, 180, 139));
    }//GEN-LAST:event_saveTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateReservation dialog = new UpdateReservation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSeparator Separator4;
    private javax.swing.JPanel background;
    private javax.swing.JPanel bar;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JLabel customerNameTxt;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField numberOfPeopleText;
    private javax.swing.JLabel numberOfPeopleTxt;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JLabel salirTxt;
    private javax.swing.JPanel saveBtn;
    private javax.swing.JLabel saveTxt;
    private javax.swing.JTextField timeText;
    private javax.swing.JLabel timeTxt;
    // End of variables declaration//GEN-END:variables
}
